### ISSUE TITLE
Halo65 keys support

### ISSUE THREAD

**Issue by mishamyrt** [mishamyrt/nuga-app#23]
In order to add full support for key configuration (and reset to default state) a keyboard state dump is required.

The dump MUST be taken from the default state. Therefore, be sure to reset the keyboard settings before dumping.

To do this, press <kbd>Fn</kbd> + <kbd>X</kbd> + <kbd>B</kbd> for a few seconds. When the reset is done, the backlight will switch to another mode and the sidelight indicator will blink.

**Comment by mishamyrt** [comment]
@Quoorex unfortunately dumps made by other applications are not suitable for me. In order to get a suitable dump, I need to install the latest version of Nuga, go to the Keys tab and click the save dump button.

**Comment by Quoorex** [comment]
Here you go, I dumped the state of my Halo65:

[Halo65.nuga.json](https://github.com/mishamyrt/nuga-app/files/14641713/Halo65.nuga.json)

Thank you very much for all the effort you put into developing this app!
